Pol 316 add savings aws old snapshots
flexera/policy_templates pull request #590
Opened 2020-08-25 15:39 UTC by gopinathmahakud1

### Description

Added savings in the incidents

### Issues Resolved

- Include Estimated Monthly Savings to each resource
- Include Total Estimated Monthly Savings in the incident summary

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5f452e60256320000191fe4a
![image](https://user-images.githubusercontent.com/55230965/91195814-f988a480-e716-11ea-81c9-1bc45113f9b6.png)

2020-08-26 02:23 UTC, gopinathmahakud1 commented
I have fixed the conflict and committed the changes. Thanks

2020-08-27 19:54 UTC, cdwilhelm commented on cost/aws/old_snapshots/README.md
> +This policy finds AWS snapshots in the given account which are older than the specified days and deletes them after user approval. For a snapshot, if images are created then we can't delete the snaps
please add Estimated Savings detail to the readme.  See the POL epic for an example.  I'll update the other policies with the new readme content.

2020-09-10 18:43 UTC, cdwilhelm requested changes

2020-09-10 18:43 UTC, cdwilhelm commented on cost/aws/old_snapshots/README.md
> +The Estimated Savings and Estimated Monthly Savings rounded to 3 decimal places, so the savings value will display $0.000 if estimated savings is less than $0.0005.
should this be Estimated Monthly Saving and Total Estimated Monthly savings?

2020-09-16 18:56 UTC, cdwilhelm submitted a review, later dismissed
LGTM, thanks

2020-10-08 22:58 UTC, cdwilhelm approved these changes

2020-10-08 22:58 UTC, merged

2020-10-21 22:07 UTC, douglaswth commented on cost/aws/old_snapshots/CHANGELOG.md
> +## v2.6
This version bump was not actually included in the actual Policy Template file, so it probably wasn't published.