POL-410-Use-idle-IP-costs-for-displaying-total-savings-in-AWS-unused-IP-address-policy
flexera/policy_templates pull request #647
Opened 2020-12-15 11:56 UTC by KVivek03

POL-410-Use-idle-IP-costs-for-displaying-total-savings-in-AWS-unused-IP-address-policy

Modified policy to only use Idle costs from Optima for calculating the total estimated monthly savings

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2020-12-15 18:51 UTC, douglaswth requested changes
With this change it would also make sense to put the per unattached IP address estimated savings into the `export` by dividing the total estimated savings by the number of unattached IP addresses.

2020-12-16 04:29 UTC, KVivek03 commented
Hi @douglaswth ,
I am not sure if the splitting would be showing the per-resource cost correctly, as for the testing purpose when I applied the policy for this account - 123812461563, We are seeing cost for only one IP from Optima
![image](https://user-images.githubusercontent.com/61958294/102305038-03177000-3f85-11eb-9d8c-e2d8a2eaa92d.png)
but there are in total 11 unused IPs. So by the suggested approach we would be showing one IP cost splitted among 11 of them. Please let me know your thoughts.

2020-12-16 18:44 UTC, douglaswth commented
That does not seem like a very useful approach. We should not just be passing whatever costs we're seeing in Optima as if they are the total estimate, but rather we should use the data in Optima to determine what the cost per month of a single unused IP address would be and then you can multiply that by the count of unused IP addresses that the policy has discovered to get the total estimated savings and you can report the individual estimated savings easily as well.

2020-12-17 15:27 UTC, KVivek03 commented
Hi @douglaswth , If we are checking for monthly cost for the IPs and selecting any one of them and then calculating and dividing among the discovered unused IP by policy, It can lead to showing incorrect results as the **IPs are charged hourly. Moreover there can be few IPs unused from 15 or 20 or even 30 days.** So calculating on the basis of one and showing as savings would not be giving the correct estimated savings information. The general approach which we are using is to find for 1 day and show it for a month after multiplying with 30 which is also mentioned in README. Since Optima does not have the AWS IPs id, we show the sum total of the entire received cost data from Optima.
Please let us know your thoughts.

2020-12-17 22:25 UTC, douglaswth commented
If you cannot figure out what the estimated savings for a single unused IP address is, I don't see how the current methodology could possibly give an accurate total estimate. An estimate is a future looking calculation based on the current run rate, not something based on what has already happened previously.

If you can find the costs for 1 day, you should be able to figure out from that what the hourly rate is for a single unused IP address from that and use it to actually calculate out the estimated savings over a month that would be realized if each of the unused IP addresses detected were to be removed. If that is not actually possible currently with the data that you are getting from Optima, then I think we should consider figuring out a different solution as I don't believe the current solution is going to be accurate otherwise.

2020-12-18 16:27 UTC, KVivek03 commented
Hi @douglaswth , I had a discussion with @nshivappa and we thought since the cost seems to be fixed for Unused IPs which is $0.005 per hour so should we show the estimated savings as per this data for the remaining days. For example if user ran the policy , so our policy will consider remaining days of the current month(13 days if ran today)*24(hour)*0.005 to compute the estimated savings per-resource for this month and then we would multiply this value by discovered unused IPs to show total estimated savings.
We would be mentioning the same in the readme file. PFB the price documentation page-
https://aws.amazon.com/ec2/pricing/on-demand/#Elastic_IP_Addresses
We have found out one of the API which is also giving the same information based on location, PFB the snap of the api response:
![image](https://user-images.githubusercontent.com/61958294/102637412-f90b9200-417b-11eb-93a8-5ca15bcbe05e.png)

Please let us know your suggestions, Thanks

2020-12-18 22:50 UTC, douglaswth commented
Using the $0.005 per hour pricing makes sense as long as there are no other discounts involved. However, I don't think you should be considering how many days are remaining in a month for calculating the estimate; the `README.md` already states that the estimate is supposed to be a 30 day estimate, so you should be multiplying the price out to that for the estimate.

2020-12-21 14:29 UTC, KVivek03 commented
Hi @douglaswth , We tried to research for API which gives the discount details but we are unable to find. We have found out this api -https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetSavingsPlansCoverage.html, but it seems to be giving on the account level, not specific to idle elastic ips. Please let us know your suggestions. Should we calculate using the $0.005*hour*30 and show per resource and mention in the readme that it is excluding the discounts applied?
cc @nshivappa

2020-12-21 19:11 UTC, douglaswth commented
Yes, that seems reasonable for now.

2020-12-23 15:34 UTC, KVivek03 commented
Hi @douglaswth , We have modified the policy to display savings per resource and total estimated savings using only the per hour IP idle costs for a period of 30 days excluding the discounts, and same we have mentioned in the readme.
Hi @nshivappa , requesting you to kindly review the PR.

2020-12-23 19:07 UTC, douglaswth commented on cost/aws/unused_ip_addresses/README.md
> -- billing_center_viewer (note: this role must be applied at the Organization level)
Are you still getting currency information from Optima? If so, you probably need some role in the Flexera One or legacy RightScale platform.

2020-12-23 19:07 UTC, douglaswth commented on cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
> +    query "apikey", "5f996aab23fb4f368057a28bc91b83b1"
Should we really have a hard coded API key here?

2021-01-15 12:15 UTC, nshivappa reviewed
LGTM

2021-01-19 12:08 UTC, nshivappa submitted a review, later dismissed

2021-01-19 12:12 UTC, KVivek03 commented
Hi @douglaswth , requesting your approval for the changes. Kindly review the PR Thanks.

2021-01-19 23:35 UTC, douglaswth requested changes
Things are looking good! I just have one suggestion for a wording change in the `README.md`.

2021-01-19 23:35 UTC, douglaswth commented on cost/aws/unused_ip_addresses/README.md
> +Please note that the estimated savings is calculated and displayed in USD($), excluding the discounts.
```suggestion
Please note that the estimated savings is calculated and displayed in USD($), excluding any discounts.
```

2021-01-20 18:47 UTC, douglaswth approved these changes

2021-01-21 05:16 UTC, merged