POL 395 azure mca reservation recommendations/expiration
flexera/policy_templates pull request #652
Opened 2021-01-20 14:47 UTC by gopinathmahakud1

### Description

Azure mca reservation recommendations/expiration new policy

### Issues Resolved

- Creating a new policy for azure MCA  reservation recommendations and expiration

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/60083e68b6b47d0001c87194
![image](https://user-images.githubusercontent.com/55230965/105190276-d9410280-5b5b-11eb-986e-28b69d69f9e5.png)
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/60083d7c67016a000156f991
![image](https://user-images.githubusercontent.com/55230965/105190437-01306600-5b5c-11eb-8867-3e799ae2fb31.png)

2021-01-21 14:41 UTC, cdwilhelm requested changes
looks very good.  just a few minor changes.

2021-01-27 16:36 UTC, gopinathmahakud1 commented on cost/azure/reserved_instances/mca_expiration/README.md
> +This Policy Template leverages the [Azure EA API](https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/reservationorder/list). It will notify only if expiration is within the time frame sp
I have addressed.

2021-01-27 16:36 UTC, gopinathmahakud1 commented on cost/azure/reserved_instances/mca_expiration/README.md
> +Provider tag value to match this policy: `azure`
I have addressed.

2021-01-27 16:37 UTC, gopinathmahakud1 commented on cost/azure/reserved_instances/mca_expiration/azure_reserved_instance_expiration.pt
> +    end
I have addressed.

2021-01-27 16:37 UTC, gopinathmahakud1 commented on cost/azure/reserved_instances/mca_recommendations/README.md
> +Provider tag value to match this policy: `azure`
I have addressed.

2021-01-27 16:37 UTC, gopinathmahakud1 commented on cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
> +      resource_level true
I have addressed.

2021-01-27 16:37 UTC, gopinathmahakud1 commented on cost/azure/reserved_instances/mca_expiration/azure_reserved_instance_expiration.pt
> +      resource_level true
I have addressed.

2021-01-27 16:40 UTC, cdwilhelm commented
@gopinathmahakud1   thank you. I'm going to get some feedback from the customer.

2021-02-01 13:40 UTC, gopinathmahakud1 commented
@cdwilhelm Do you have any customer feedback for this?

2021-02-04 18:11 UTC, cdwilhelm commented
> @cdwilhelm Do you have any customer feedback for this?

Very little feedback so far.  There is an issue with one policy which I'm trying to help them on.  I'll get back to you in the next day or two.

2021-03-16 20:48 UTC, cdwilhelm approved these changes

2021-03-16 20:48 UTC, merged