Azure hybrid use benefit linux
flexera/policy_templates pull request #662
Opened 2021-03-12 14:49 UTC by charmeling

### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2021-03-15 16:07 UTC, cdwilhelm submitted a review, later dismissed

2021-03-15 16:07 UTC, cdwilhelm commented on cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
> +## v1.0
should be v2.0

2021-03-15 16:07 UTC, cdwilhelm commented on cost/azure/hybrid_use_benefit_linux/README.md
> +Since November 2020 Microsoft also offers AHUB for certain Linux instances. This Policy Template is used to automatically apply the Azure Hybrid Use Benefit (AHUB) to all eligible Linux VMs in an Azu
The first sentence isn't necessary.

2021-03-15 16:07 UTC, cdwilhelm commented on cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
> +  version: "1.0",
should be version 2.0

2021-03-15 16:07 UTC, cdwilhelm commented on cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
> +  service: "",
What is the service, Compute?

2021-03-15 16:55 UTC, charmeling commented on cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
> +## v1.0
Applied changes

2021-03-15 17:04 UTC, charmeling commented
> This looks great @charmeling!
> Do you have a running example I could take a look at?
@srpomeroy - yes I tested it in the ThierryCorp org, not sure if you have access to it?
> Can you tell me what happens if you try to apply SLES AHUB to a RHEL VM and vice versa?
You got me ;-)
It depends on the distribution. 
For RHEL (applying SLES AHUB): license_type is set to "SLES_BYOS" but nothing really happens (if I check in the Azure console, no changes are shown.
For SLES (applying RHEL AHUB): error message in Postman that the action cannot be completed because Red Hat Cloud Access hasn't been enabled on my Azure subscription. However, if this would be the case, I would expect that similar to RHEL the wrong license_type would be set...
For SLES (applying SLES AHUB): it works - license_tpye=SLES_BYOS, also reflected in the Azure Console

I imagine, I need to define allowed values for both escalations, right?

2021-03-15 19:38 UTC, srpomeroy commented
I am thinking we may only need a single escalation with logic that checks for the appropriate distro and applies the relevant BYOL string.

2021-03-16 07:09 UTC, charmeling commented
@srpomeroy - Yes, that's a good idea, will see what I can do and update you.

2021-03-16 07:47 UTC, charmeling commented
@srpomeroy - Yes, that's a good idea, I assume the check needs to be done in the js part, right? Or can I also do checks within the policy, escalation, workflow definitions? Will see what I can do...

2021-03-16 09:15 UTC, charmeling commented
@srpomeroy - Did change it a bit. Now it checks what distribution is being used and only needs one single escalation. I could also verify in the CWF console in Rightscale that when doing the workflow part with a RHEL VM, it complains to activate cloud access in RedHat (see attachment)...
![rhel_message0](https://user-images.githubusercontent.com/58976080/111284411-624a5680-8640-11eb-83c2-113b3f0c32a9.png)

2021-03-17 15:37 UTC, charmeling reviewed
Applied changes as requested

2021-03-17 15:52 UTC, srpomeroy requested changes
Just a few minor tweaks.

2021-03-17 15:52 UTC, srpomeroy commented on cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
> +#escalation "license_rhel_instances" do
If we are good without this escalation block, let's go ahead and delete it.

2021-03-17 19:10 UTC, srpomeroy approved these changes
LGTM. Please just do me a favor @charmeling and fill out the initial post of this PR with information about the policy for reference.

2021-03-17 19:11 UTC, srpomeroy commented
Any final remarks @cdwilhelm ?

2021-03-17 22:10 UTC, cdwilhelm commented
@charmeling @srpomeroy nothing more from me. 
good work @charmeling

2021-03-17 22:11 UTC, cdwilhelm approved these changes
LGTM

2021-03-18 13:47 UTC, merged