Adding HWMFA policy
flexera/policy_templates pull request #724
Opened 2021-08-31 16:09 UTC by XOmniverse

### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2021-08-31 16:10 UTC, XOmniverse commented
Set to "DO NOT MERGE" since I can't properly test it against hardware MFA being enabled. This is for code review.

2021-08-31 16:29 UTC, rshade requested changes

2021-08-31 16:29 UTC, rshade commented on security/aws/iam_hwmfa_enabled_for_root/aws_iam_hwmfa_enabled.pt
> +  nist: "AC-6(9)"
These need to be updated from the docs.

2021-08-31 16:29 UTC, rshade commented on security/aws/iam_hwmfa_enabled_for_root/aws_iam_hwmfa_enabled.pt
> +escalation "report_no_hwmfa" do
We start all escalations with `esc`

2021-09-07 15:13 UTC, XOmniverse commented
@rshade This should be the final correct version based on our testing. Awaiting review.

2021-09-07 16:03 UTC, rshade requested changes

2021-09-07 16:03 UTC, rshade commented on security/aws/iam_hwmfa_enabled_for_root/aws_iam_hwmfa_enabled.pt
> +  cis_controls: "[\"1.4\",\"3.3v8\", \"4.3v7\", \"5.4v8\"]",
Can you update these?

2021-09-07 16:30 UTC, XOmniverse commented on security/aws/iam_hwmfa_enabled_for_root/aws_iam_hwmfa_enabled.pt
> +  cis_controls: "[\"1.4\",\"3.3v8\", \"4.3v7\", \"5.4v8\"]",
> Can you update these?

Done.

2021-09-13 16:32 UTC, rshade approved these changes
LGTM

2021-09-13 16:34 UTC, rshade requested changes
Can you add this one and the one we already merged to the root readme?

2021-09-13 17:13 UTC, XOmniverse commented
> Can you add this one and the one we already merged to the root readme?

Done

2021-09-13 17:22 UTC, rshade approved these changes

2021-09-13 17:23 UTC, rshade approved these changes
LGTM

2021-09-13 17:27 UTC, merged