Pol 467 disable 45 day creds
flexera/policy_templates pull request #735
Opened 2021-09-17 19:34 UTC by XOmniverse

### Description

Verified working policy

2021-09-20 20:49 UTC, rshade submitted a review, later dismissed
LGTM

2021-09-20 21:51 UTC, rshade requested changes

2021-09-20 21:51 UTC, rshade commented on security/aws/iam_disable_45_day_creds/CHANGELOG.md
> +## v2.1
remove this one por favor

2021-09-21 13:01 UTC, XOmniverse commented on security/aws/iam_disable_45_day_creds/CHANGELOG.md
> +## v2.1
You got it

2021-09-24 12:32 UTC, rshade approved these changes
LGTM

2021-09-24 13:02 UTC, merged