Pol 477 expired ssl certs
flexera/policy_templates pull request #748
Opened 2021-09-28 13:17 UTC by XOmniverse

### Description

Adds policy to check AWS account for expired IAM SSL certificates.

2021-10-07 19:28 UTC, rshade requested changes

2021-10-07 19:28 UTC, rshade commented on security/aws/iam_expired_ssl_certs/iam_expired_ssl_certs.pt
> +        bad_cert_list.push(cert.Arn + " expired on " + expiration.toString())
can we make this { arn: "", expiration:"", account: ""} so we can iterate them in the export?

2021-10-07 19:28 UTC, rshade commented on security/aws/iam_expired_ssl_certs/iam_expired_ssl_certs.pt
> +      field "id" do
Update this for new fields in the array.

2021-10-07 20:30 UTC, XOmniverse commented
@rshade requested changes made

2021-10-08 12:45 UTC, rshade approved these changes
LGTM

2021-10-08 13:02 UTC, merged