Fixing Editorconfig violations
flexera/policy_templates pull request #790
Opened 2021-11-12 22:05 UTC by rshade

### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2021-11-15 23:52 UTC, douglaswth requested changes

2021-11-15 23:52 UTC, douglaswth commented on cost/low_service_usage/low_service_usage.pt
>      }
```suggestion
      }
```

2021-11-15 23:52 UTC, douglaswth commented on cost/low_service_usage/low_service_usage.pt
> +  var start_at = year + "-" + pad(month) + '-01'
```suggestion
    var end_at = year + "-" + pad(month) + "-" + pad(yesterday)
    var start_at = year + "-" + pad(month) + '-01'
```

2021-11-15 23:52 UTC, douglaswth commented on cost/scheduled_reports/scheduled_report.pt
>        start_at = getFormattedMonthlyDate(addMonths(now, -totalMonth));
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on cost/scheduled_reports/scheduled_report.pt
> +      count=0;
```suggestion
        count=0;
```

2021-11-15 23:52 UTC, douglaswth commented on cost/scheduled_reports/scheduled_report.pt
>        _.each(previousMonths, function(month){
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on cost/scheduled_reports/scheduled_report.pt
>          categories.push("Other");
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on cost/scheduled_reports_with_estimates/costs_forecasting.pt
>          if(isNaN(month2)){
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on cost/superseded_instance_remediation/superseded_instance_remediation.pt
> +    end
```suggestion
      field "locked" do
        label "Locked"
      end
      field "href" do
        label "Href"
      end
```

2021-11-15 23:52 UTC, douglaswth commented on cost/volumes/test_code/hash_dump_tester.pt
>      validate_each $ds_unattached_volumes do
```suggestion
  validate_each $ds_unattached_volumes do
```

2021-11-15 23:52 UTC, douglaswth commented on cost/volumes/test_code/hash_dump_tester.pt
> +  check eq(0,1)
```suggestion
    # Go through the unattached volumes that were found by the script-based datasource above
    # and check if not older than specified number of days.
    # If the check fails, it'll flag the volume
    #check le(val(item, "age"), $param_days_old)
    check eq(0,1)
```

2021-11-15 23:52 UTC, douglaswth commented on cost/volumes/test_code/hash_dump_tester.pt
> +  #escalate $esc_unattached_volumes
```suggestion
    #escalate $esc_unattached_volumes
```

2021-11-15 23:52 UTC, douglaswth commented on cost/volumes/test_code/hash_dump_tester.pt
> +  summary_template "Hash Dumps"
```suggestion
    summary_template "Hash Dumps"
```

2021-11-15 23:52 UTC, douglaswth commented on cost/volumes/test_code/hash_dump_tester.pt
> +      detail_template <<-EOS
```suggestion
    detail_template <<-EOS
```

2021-11-15 23:52 UTC, douglaswth commented on cost/volumes/test_code/javascript_object_testing.js
> +    console.log(JSON.stringify(test_obj))
```suggestion
  {
    a: "11",
    c: "goo"
  },
];
console.log(JSON.stringify(test_obj));
```

2021-11-15 23:52 UTC, douglaswth commented on cost/volumes/test_code/javascript_object_testing.js
> +      }
```suggestion
for (var i = 0; i < test_obj.length; i++) {
  //if (typeof test_obj[i]["b"] == "object") {
  if (test_obj[i]["b"]) {
    console.log("Found b; index: "+i)
  } else if (test_obj[i]["c"]) {
    console.log("Found c; index: "+i)
  } else {
    console.log("Found nothing; index: "+i)
  }
}
```

2021-11-15 23:52 UTC, douglaswth commented on operational/aws/instance_scheduled_events/README.md
>    policy. The information below should be consulted when creating the credential.
```suggestion
credential registered in the system that is compatible with this policy. If
there are no credentials listed when you apply the policy, please contact your
cloud admin and ask them to register a credential that is compatible with this
policy. The information below should be consulted when creating the credential.
```

2021-11-15 23:52 UTC, douglaswth commented on operational/aws/lambda_functions_with_high_error_rate/README.md
>  }
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on operational/aws/long_running_instances/README.md
> +  approval from the Policy Approver. This policy includes the following actions.
```suggestion
Policy Incident. Actions that destroy or terminate a resource generally require
approval from the Policy Approver. This policy includes the following actions.
```

2021-11-15 23:52 UTC, douglaswth commented on operational/aws/long_running_instances/README.md
>    policy. The information below should be consulted when creating the credential.
```suggestion
credential registered in the system that is compatible with this policy. If
there are no credentials listed when you apply the policy, please contact your
cloud admin and ask them to register a credential that is compatible with this
policy. The information below should be consulted when creating the credential.
```

2021-11-15 23:52 UTC, douglaswth commented on operational/aws/subnet_name_sync/aws_subnet_name_sync.pt
> +    field "region", val(iter_item,"region")
```suggestion
      field "region", val(iter_item,"region")
```

2021-11-15 23:52 UTC, douglaswth commented on operational/aws/subnet_name_sync/aws_subnet_name_sync.pt
> +  escalate $email
```suggestion
    escalate $email
```

2021-11-15 23:52 UTC, douglaswth commented on operational/aws/vpc_name_sync/aws_vpc_name_sync.pt
> +    field "region", val(iter_item,"region")
```suggestion
      field "region", val(iter_item,"region")
```

2021-11-15 23:52 UTC, douglaswth commented on operational/aws/vpc_name_sync/aws_vpc_name_sync.pt
> +  escalate $email
```suggestion
    escalate $email
```

2021-11-15 23:52 UTC, douglaswth commented on operational/azure/sync_tags_with_optima/sync_azure_tags.pt
> +  $response = http_request(
```suggestion
    $response = http_request(
```

2021-11-15 23:52 UTC, douglaswth commented on operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
> +    field "subscriptionName", jmes_path(col_item,"displayName")
```suggestion
      field "subscriptionName", jmes_path(col_item,"displayName")
```

2021-11-15 23:52 UTC, douglaswth commented on operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
> +      field "subscriptionName", val(iter_item,"subscriptionName")
```suggestion
        field "subscriptionName", val(iter_item,"subscriptionName")
```

2021-11-15 23:52 UTC, douglaswth commented on operational/dbaas/aws/rds_backup/README.md
> +  }]
```suggestion
    }
  ]
```

2021-11-15 23:52 UTC, douglaswth commented on operational/dbaas/aws/rds_backup/README.md
>  ```javascript
```suggestion
```json
```

2021-11-15 23:52 UTC, douglaswth commented on operational/dbaas/aws/rds_backup/aws_rds_backup.pt
> +    field "region", val(iter_item,"region")
```suggestion
      field "region", val(iter_item,"region")
```

2021-11-15 23:52 UTC, douglaswth commented on operational/fnms/schedule_fnms_reports/schedule-fnms-report.pt
> +  }
```suggestion
    }
```

2021-11-15 23:52 UTC, douglaswth commented on operational/stranded_servers/stranded_servers.pt
> +    // Constructing tags with comma separated to display in detail_template
```suggestion
      // Constructing tags with comma separated to display in detail_template
```

2021-11-15 23:52 UTC, douglaswth commented on saas/fsm/redundant_apps/fsm-redundant_apps.pt
> +  }else{
```suggestion
    }else{
```

2021-11-15 23:52 UTC, douglaswth commented on saas/fsm/redundant_apps/fsm-redundant_apps.pt
> +  }
```suggestion
    }
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/clb_unencrypted/aws_clb_encryption.pt
> +          loadBalancerProtocol: protocols[x],
```suggestion
                loadBalancerProtocol: protocols[x],
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/ebs_unencrypted_volumes/aws_unencrypted_volumes.pt
> +    field "region", val(iter_item,"region")
```suggestion
      field "region", val(iter_item,"region")
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/ebs_unencrypted_volumes/aws_unencrypted_volumes.pt
> +  }
```suggestion
    }
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/ebs_unencrypted_volumes/aws_unencrypted_volumes.pt
> +    }
```suggestion
      }
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/elb_unencrypted/aws_elb_encryption.pt
> +        loadBalancerProtocol: protocol,
```suggestion
              loadBalancerProtocol: protocol,
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/loadbalancer_internet_facing/aws_internet-facing_elbs.pt
> +  content = _.sortBy(content, 'region');
```suggestion
    content = _.sortBy(content, 'region');
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/loadbalancer_internet_facing/aws_internet-facing_elbs.pt
>      end
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +  content = _.sortBy(content, 'region');
```suggestion
    content = _.sortBy(content, 'region');
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
>        verb: "get",
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +    "PubliclyAccessible": false,
```suggestion
        "PubliclyAccessible": false,
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
>        verb: "get",
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +    "DBClusterIdentifier": $item["db_cluster_identifier"],
```suggestion
        "DBClusterIdentifier": $item["db_cluster_identifier"],
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +      $describe_cluster_snapshot = http_request(
```suggestion
          $describe_cluster_snapshot = http_request(
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +          "DeleteAutomatedBackups": false,
```suggestion
              "DeleteAutomatedBackups": false,
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +      $response = http_request(
```suggestion
          $response = http_request(
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +          "DeleteAutomatedBackups": false,
```suggestion
              "DeleteAutomatedBackups": false,
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +    $response = http_request(
```suggestion
        $response = http_request(
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +          "DeleteAutomatedBackups": false,
```suggestion
              "DeleteAutomatedBackups": false,
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
>      )
```suggestion
          "FinalDBSnapshotIdentifier": $item["id"]+"-finalSnapshot"
        }
      )
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
>      )
This block might need some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_unencrypted/README.md
>      {
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_unencrypted/aws_unencrypted_rds_instances.pt
> +      query_strings: {
```suggestion
          auth: $$auth_aws,
          https: true,
          verb: "get",
          href: "/",
          host: "rds."+$item["region"]+".amazonaws.com",
          query_strings: {
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_unencrypted/aws_unencrypted_rds_instances.pt
> +      "DBClusterSnapshotIdentifier": $item["db_cluster_identifier"]+"-finalSnapshot"
```suggestion
            "DBClusterSnapshotIdentifier": $item["db_cluster_identifier"]+"-finalSnapshot"
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_unencrypted/aws_unencrypted_rds_instances.pt
> +      $response = http_request(
```suggestion
          $response = http_request(
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/rds_unencrypted/aws_unencrypted_rds_instances.pt
> +    end
```suggestion
        end
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/unencrypted_s3_buckets/README.md
>  ```javascript
```suggestion
```ruby
```

2021-11-15 23:52 UTC, douglaswth commented on security/aws/vpcs_without_flow_logs_enabled/README.md
>      {
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on security/azure/sql_publicly_accessible_managed_instance/check_for_publicly_accessible_azure_sql_managed_instance.pt
> +  res = _.sortBy(res, 'location');
```suggestion
    res = _.sortBy(res, 'subscriptionName');
    res = _.sortBy(res, 'location');
```

2021-11-15 23:52 UTC, douglaswth commented on security/azure/sql_publicly_accessible_managed_instance/check_for_publicly_accessible_azure_sql_managed_instance.pt
> +    auth: $$azure_auth,
```suggestion
        auth: $$azure_auth,
```

2021-11-15 23:52 UTC, douglaswth commented on security/storage/aws/public_buckets/README.md
>      ]
This block needs some more indentation overhaul.

2021-11-15 23:52 UTC, douglaswth commented on security/storage/google/public_buckets/google_public_buckets.pt
>    result=_.sortBy(result, 'name')
This block needs some more indentation overhaul.

2021-11-16 18:22 UTC, douglaswth requested changes

2021-11-16 18:22 UTC, douglaswth commented on cost/aws/object_storage_optimization/README.md
>  ```javascript
```suggestion
```json
```

2021-11-16 18:22 UTC, douglaswth commented on cost/aws/s3_bucket_size/README.md
>  ```javascript
```suggestion
```json
```

2021-11-16 18:22 UTC, douglaswth commented on cost/aws/unused_rds/README.md
>  ```javascript
```suggestion
```json
```

2021-11-16 18:22 UTC, douglaswth commented on cost/aws/unused_volumes/aws_delete_unused_volumes.pt
> +  end
This block needs some more indentation overhaul.

2021-11-16 18:22 UTC, douglaswth commented on cost/aws/unused_volumes/aws_delete_unused_volumes.pt
> +  end
All the way up to `result do`.

2021-11-16 18:22 UTC, douglaswth commented on cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
>      sub on_error: rollback($item, $param_google_project) do
```suggestion
      sub on_error: rollback($item, $param_google_project) do
```

2021-11-16 18:22 UTC, douglaswth commented on operational/aws/lambda_functions_with_high_error_rate/README.md
>  ```javascript
```suggestion
```json
```

2021-11-16 18:22 UTC, douglaswth commented on security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
> +      #Creating Cluster snapshot manually Since DB instance snapshot cannot be created directly for Aurora cluster DB instance.
```suggestion
        #Creating Cluster snapshot manually Since DB instance snapshot cannot be created directly for Aurora cluster DB instance.
```

2021-11-16 18:22 UTC, douglaswth commented on security/aws/rds_unencrypted/README.md
>  ```javascript
```suggestion
```json
```

2021-11-16 18:22 UTC, douglaswth commented on security/aws/vpcs_without_flow_logs_enabled/README.md
>  ```javascript
```suggestion
```json
```

2021-11-16 18:22 UTC, douglaswth commented on security/storage/aws/public_buckets/README.md
>  ```javascript
```suggestion
```json
```

2021-11-16 19:03 UTC, rshade commented on compliance/google/unlabeled_resources/unlabeled_resources.pt
> +    var result = [];
I pulled it out and let code format document it to fix this. Will post

2021-11-16 20:23 UTC, douglaswth requested changes
Looks like there are just these last few remaining now.

2021-11-16 20:23 UTC, douglaswth commented on compliance/aws/long_stopped_instances/aws_long_stopped_instances.pt
> +    if(instance_stopped["instance_id"] == cloudwatch_metrics["instance_id"] && cloudwatch_metrics['datapoints'].length == 0 && !is_tag_matched){
```suggestion
      //If the EC2 instance tag does not match with entered param_exclude_tags and cloud metrics is empty,
      if(instance_stopped["instance_id"] == cloudwatch_metrics["instance_id"] && cloudwatch_metrics['datapoints'].length == 0 && !is_tag_matched){
```

2021-11-16 20:23 UTC, douglaswth commented on operational/aws/lambda_functions_with_high_error_rate/README.md
>  ```javascript
```suggestion
```json
```

2021-11-16 20:26 UTC, douglaswth commented on compliance/disallowed_images/disallowed_cloud_images.pt
> +  _.each(ds_instances_list, function(instance){
```suggestion
    var content=[]
    _.each(ds_instances_list, function(instance){
```
One last one. 🤣

2021-11-16 21:11 UTC, douglaswth commented on compliance/aws/long_stopped_instances/aws_long_stopped_instances.pt
> +      if(instance_stopped["instance_id"] == cloudwatch_metrics["instance_id"] && cloudwatch_metrics['datapoints'].length == 0 && !is_tag_matched){
```suggestion
        //If the EC2 instance tag does not match with entered param_exclude_tags and cloud metrics is empty,
        if(instance_stopped["instance_id"] == cloudwatch_metrics["instance_id"] && cloudwatch_metrics['datapoints'].length == 0 && !is_tag_matched){
```
This one seems to keep coming up?

2021-11-16 21:18 UTC, douglaswth approved these changes
LGTM

2021-11-16 21:29 UTC, merged